import React from "react";
import { StyleSheet } from "react-native";
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveScreenFontSize,
  responsiveScreenHeight,
  responsiveWidth,
} from "react-native-responsive-dimensions";
import { appColor, COLORS } from "../constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appColor.white,
  },
  ImageSlider: {
    width: responsiveWidth(98),
    alignSelf: "center",
    marginBottom: responsiveHeight(1),
  },
  CardView: {
    // marginVertical: responsiveHeight(1.5),
    // backgroundColor: "white",
    borderRadius: responsiveWidth(3),
    // height: responsiveHeight(12),
    // width: responsiveWidth(90),
    // alignSelf: "center",
    // justifyContent: "space-evenly",
    // flexDirection: "row",
    // alignItems: "center",
    // shadowColor: "#000",
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.23,
    // shadowRadius: 2.62,

    // elevation: 4,
    marginVertical: responsiveHeight(1.5),
    marginHorizontal: responsiveWidth(2),
    backgroundColor: "white",
    height: responsiveHeight(8),
    width: responsiveWidth(70),
    alignSelf: "center",
    justifyContent: "space-evenly",
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,

    elevation: 4,
  },
  FlatListImages: {
    height: responsiveHeight(8),
    width: responsiveWidth(16),
  },
  descriptionView: {
    width: responsiveWidth(40),
  },
  TitleText: {
    fontSize: responsiveScreenFontSize(1.8),
    fontWeight: "bold",
    marginBottom: responsiveHeight(1),
  },
  descriptionTxt: {
    fontSize: responsiveFontSize(1),
  },
  OrderNowView: {
    backgroundColor: appColor.Primary,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: responsiveWidth(3),
    marginTop: responsiveHeight(1),
    width: responsiveWidth(23),
    alignSelf: "center",
  },
  OrderText: {
    alignSelf: "center",
    fontSize: responsiveFontSize(1.5),
    fontWeight: "bold",
    color: appColor.Textred,
    marginVertical: responsiveHeight(0.7),
  },
  PriceView: {
    backgroundColor: appColor.ViewRed,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: responsiveWidth(3),
    marginTop: responsiveHeight(1),
    width: responsiveWidth(29),
  },
  PriceTxt: {
    fontSize: responsiveFontSize(1.6),
    color: appColor.white,
    fontWeight: "500",
    marginVertical: responsiveHeight(0.6),
    marginHorizontal: responsiveWidth(0.5),
  },
  centeredView: {
    flex: 1,    
    backgroundColor: COLORS.iconbgblack,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    margin: 20,
    borderRadius: responsiveWidth(3),
    backgroundColor: "white",
    height: responsiveHeight(85),
    width: responsiveWidth(90),
    // alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalbtn: {
    backgroundColor: appColor.Textred,
    borderRadius: responsiveWidth(3),
    width: responsiveWidth(90),
    alignItems: "center",
    paddingVertical: responsiveHeight(1),
  },
  btntxt: {
    color: appColor.primary,
  },
  sizeView: {
    flexDirection: "row",
    width: responsiveWidth(45),
    marginTop: responsiveHeight(1),
    justifyContent: "space-between",
    marginLeft: responsiveWidth(4),
  },
  modalText: {
    color: appColor.Textred,
    fontSize: responsiveFontSize(2.8),
    marginLeft: responsiveWidth(4),
    marginTop: responsiveHeight(2),
    fontWeight: "500",
  },
  priceContainer: {
    backgroundColor: appColor.Textred,
    borderRadius: responsiveWidth(5),
    width: responsiveWidth(65),
    marginLeft: responsiveWidth(4),
    marginTop: responsiveHeight(2),
    paddingVertical: responsiveHeight(0.1),
    paddingLeft: responsiveWidth(2),
  },
  listHeadertxt: {
    color: appColor.secondary,
    marginLeft: responsiveWidth(11),
    marginTop: responsiveHeight(2),
    fontSize: responsiveFontSize(2),
    fontWeight: "500",
  },
  FlatListView: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: responsiveWidth(4),
    // marginTop: responsiveHeight(2),
  },
  name: {
    marginLeft: responsiveWidth(2),
    width: responsiveWidth(50),
    color: "black",
  },
  subtxt: {
    color: appColor.Textred,
    fontSize: responsiveFontSize(2),
    textAlign: "right",
    marginRight: responsiveWidth(10),
    marginTop: responsiveHeight(2),
    marginBottom: responsiveHeight(1),
  },
  crossbutton: {
    backgroundColor: "black",
    height: responsiveWidth(7),
    width: responsiveWidth(7),
    // alignSelf: "flex-end",
    position: "absolute",
    borderRadius: responsiveWidth(3.5),
    alignItems: "center",
    justifyContent: "center",
    right: responsiveWidth(-1),
    top: responsiveHeight(-1),
  },
});
